CREATE TABLE "sprints" (
	"id" BIGINT NOT NULL DEFAULT NULL,
	"name" VARCHAR(255) NOT NULL DEFAULT NULL,
	"startDate" DATE NOT NULL DEFAULT NULL,
	"endDate" DATE NOT NULL DEFAULT NULL,
	"status" INT NOT NULL DEFAULT '1',
	"team" VARCHAR(50) NOT NULL DEFAULT '',
	"pointsplanned" INT NOT NULL DEFAULT '0',
	"pointscompleted" INT NOT NULL DEFAULT '0',
	PRIMARY KEY ("id")
)
;

INSERT INTO "sprints" VALUES (1, 'My First Sprint', '2016-05-17', '2016-05-19', 1, "Abraxas", NULL, NULL);