CREATE TABLE "usersbysprint" (
	"id" BIGINT NOT NULL DEFAULT NULL,
	"userid" BIGINT NOT NULL DEFAULT NULL,
	"sprintid" BIGINT NOT NULL DEFAULT NULL,
	"day01" INT NOT NULL DEFAULT '0',
	"day02" INT NOT NULL DEFAULT '0',
	"day03" INT NOT NULL DEFAULT '0',
	"day04" INT NOT NULL DEFAULT '0',
	"day05" INT NOT NULL DEFAULT '0',
	"day06" INT NOT NULL DEFAULT '0',
	"day07" INT NOT NULL DEFAULT '0',
	"day08" INT NOT NULL DEFAULT '0',
	"day09" INT NOT NULL DEFAULT '0',
	"day10" INT NOT NULL DEFAULT '0',
	PRIMARY KEY ("id")
)
;

INSERT INTO "usersbysprint" VALUES (1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO "usersbysprint" VALUES (2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
